theme: jekyll-theme-cayman

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   
source: https://github.com/ahmed605/SparkIV

zip: https://github.com/ahmed605/SparkIV/releases/download/v0.8.1/SparkIV.0.8.1.zip

   
